import { en } from "./en";

export const zh: Record<keyof typeof en, string> = { ...en,
  "view.webSearch.sources": "来自 {{provider}} 的网络来源（{{count}}）",
  "view.webSearch.consent.providerModel": "提供商：Gemini · 模型：{{model}}",
  "view.webSearch.action": "搜索网络", "view.webSearch.unavailable": "所选模式暂不支持网络搜索。", "view.webSearch.consent.title": "使用 Gemini 搜索网络？", "view.webSearch.consent.questionOnly": "只有您输入的问题会发送到 Gemini；不会发送 Vault、当前笔记、对话历史或模型凭据。", "view.webSearch.consent.recentChat": "您输入的问题和有限的近期聊天上下文将发送到 Gemini；不会发送 Vault、当前笔记或模型凭据。", "view.webSearch.consent.dataHandling": "Gemini 会依照 Google 服务的数据处理惯例处理该问题。", "view.webSearch.searchNow": "立即搜索", "view.webSearch.rememberSession": "在本次会话中记住", "view.webSearch.cancel": "取消", "view.webSearch.preparing": "正在搜索网络…", "view.webSearch.retry": "重试网络搜索", "view.webSearch.error.invalid-key": "Gemini API 密钥被拒绝。", "view.webSearch.error.quota": "Gemini 网络搜索配额暂不可用。", "view.webSearch.error.invalid-model": "此 Gemini 模型不能进行网络搜索。", "view.webSearch.error.timeout": "网络搜索超时。", "view.webSearch.error.malformed-response": "Gemini 返回了无法读取的网络搜索响应。", "view.webSearch.error.no-answer": "Gemini 未返回网络搜索回答。", "view.webSearch.error.no-sources": "Gemini 未返回可用的网络来源。", "view.webSearch.error.missing-api-key": "请在设置中添加网络搜索的 Gemini API 密钥。", "view.webSearch.error.disabled": "网络搜索已禁用。", "view.webSearch.error.unsupported-current-provider": "当前提供商暂不能进行网络搜索。", "view.webSearch.error.network": "无法连接 Gemini 进行网络搜索，请重试。",
  "settings.webSearch.heading": "网络搜索", "settings.webSearch.mode.name": "网络搜索模式", "settings.webSearch.mode.desc": "网络搜索为可选功能，发送问题前需要明确同意。", "settings.webSearch.mode.disabled": "已禁用", "settings.webSearch.mode.dedicatedGemini": "专用 Gemini", "settings.webSearch.geminiModel.name": "Gemini 模型", "settings.webSearch.geminiModel.desc": "仅用于网络搜索的 Gemini 模型。", "settings.webSearch.apiKey.name": "Gemini API 密钥", "settings.webSearch.apiKey.desc": "密钥单独保存在 Obsidian 安全存储中，不会与聊天模型密钥混用。", "settings.webSearch.apiKey.placeholder": "输入 Gemini API 密钥", "settings.webSearch.includeRecentChatContext.name": "包含近期聊天上下文", "settings.webSearch.includeRecentChatContext.desc": "每次确认的网络搜索最多发送六个近期回合（最多 6,000 个字符）。",
  "settings.interface.heading": "界面", "settings.interface.language.name": "界面语言", "settings.interface.language.desc": "选择界面语言。",
  "language.auto": "自动", "language.it": "意大利语", "language.en": "英语", "language.zh": "中文", "view.title": "Wiki Copilot", "command.open": "打开 Wiki Copilot",
  "welcome.title": "向 Wiki 提问", "welcome.description": "输入问题，开始与你的知识库对话。", "welcome.unconfigured": "模型尚未完整配置。直接提问会显示本地检索结果；配置服务商、模型和 API Key 后会自动生成回答。",
  "composer.placeholder": "询问当前知识库…", "composer.shortcut": "Enter 发送 · Shift + Enter 换行", "composer.send": "发送", "composer.stop": "停止", "composer.stopping": "正在停止…", "composer.stopAria": "停止当前回答", "composer.sendAria": "发送问题",
  "view.rebuild": "重建知识索引", "view.newConversation": "新对话", "view.ready": "索引就绪", "view.user": "你", "view.localRetrieval": "本地检索", "view.generalAnswer": " · 通用回答", "view.generalAnswerTitle": "未命中当前知识库，此回答来自模型通用知识", "view.stopped": "已停止", "view.timeout": "回答超时", "view.failed": "无法完成", "view.sources": "来源与检索依据（{{count}}）", "view.openSource": "打开来源 {{id}}：{{title}}", "view.sourceMissing": "找不到引用文档：{{path}}", "view.sourceOpenFailed": "无法打开引用文档。", "view.returnToChat": "返回聊天", "view.returnToChatUnavailable": "原始聊天已不可用。", "view.citationWarningTitle": "引用检查", "view.citationWarningInvalidIds": "回答包含无效来源标记：{{ids}}。", "view.citationWarningMissing": "回答未包含有效来源标记；请以来源列表为准。", "view.wikiLink": "Wikilink",
  "view.noChunks": "没有找到可用片段。可尝试更具体的术语，或检查 Vault 中是否存在 Wiki 知识层。", "view.selectedChunks": "选出 {{count}} 个上下文片段（候选 {{candidates}} 个{{truncated}}）。", "view.truncated": "，受上下文上限截断", "view.timeoutSources": "本次检索到的 {{count}} 个知识页面已保留，可展开查看。", "view.stoppedEmpty": "回答已停止，未生成可加入会话上下文的内容。", "view.stoppedPartial": "回答已停止；部分内容未加入会话上下文。", "view.interrupted": "回答中断：{{message}} 部分内容未加入会话上下文。", "view.retryCompatibility": "使用兼容模式重试", "view.model.streamingUnavailable": "此 Obsidian 环境不支持流式响应，已使用兼容模式。", "view.model.streamingUnsupported": "服务不支持流式响应，已使用兼容模式。", "view.model.completeResponse": "服务返回了完整响应。", "view.model.streamingUnavailableRetry": "此 Obsidian 环境不支持流式响应。请使用兼容模式重试。", "view.model.responseNotStreamable": "无法以流式方式读取响应。请使用兼容模式重试。", "view.model.streamConnectionFailed": "无法建立流式连接。请使用兼容模式重试。", "view.model.requestFailed": "模型请求失败：{{detail}}", "view.model.emptyResponse": "模型返回了空回答。", "view.busy": "上一条问题仍在处理中。你可以先编辑下一条问题。", "view.emptyQuestion": "请输入问题。", "view.preparing": "正在准备本地检索…", "view.connecting": "正在连接模型…", "view.waiting": "正在等待模型回答…", "view.connected": "模型已连接，等待回答…", "view.reading": "模型已响应，正在读取回答…", "view.receiving": "正在接收回答…",
  "view.model.invalidEndpoint": "模型 endpoint 必须使用 http 或 https。", "view.model.missingServiceName": "请先在 Wiki Copilot 设置中填写服务名称。", "view.model.missingEndpointOrModel": "请先在 Wiki Copilot 设置中填写模型 endpoint 和模型名称。", "view.model.missingApiKey": "请先在 Wiki Copilot 设置中填写 API Key。", "view.model.lengthWarning": "回答达到模型长度上限，内容可能不完整。", "view.model.contentFilterWarning": "回答受到模型内容过滤，内容可能不完整。",
  "view.model.insufficientSystemResource": "模型因服务资源不足中断了回答。", "view.model.streamInterrupted": "流式连接已中断。", "view.model.inputTooLarge": "此请求过大，无法发送。请使用缩减后的上下文重试。", "view.model.rateLimited": "服务暂时受到速率限制，请稍后重试。", "view.model.requestFailedSafe": "无法完成模型请求。", "view.retryReducedContext": "使用缩减后的上下文重试", "view.promptBudget": "请求 Token：{{used}} / {{limit}}",
  "role.schema": "结构", "role.index": "导航", "role.topic": "主题", "role.concept": "概念", "role.summary": "摘要", "role.wiki": "Wiki", "role.source": "原文", "role.other": "普通笔记",
  "settings.intro": "面向 LLM Wiki 的知识库问答插件，支持精准检索与来源引用。", "settings.model.heading": "模型服务", "settings.provider.name": "服务商", "settings.provider.desc": "选择后自动配置兼容接口地址和常用模型。", "settings.provider.custom": "其他 OpenAI 兼容服务", "settings.service.name": "服务名称", "settings.service.desc": "用于回答等待提示。", "settings.service.placeholder": "例如：硅基流动", "settings.endpoint.name": "接口地址", "settings.endpoint.desc": "填写 API 根地址，或完整的 /chat/completions 地址。", "settings.model.name": "模型", "settings.model.custom.desc": "填写服务商提供的模型 ID。", "settings.model.placeholder": "模型 ID", "settings.model.endpoint": "接口地址自动使用 {{endpoint}}", "settings.model.current": "{{model}}（当前配置）", "settings.apiKey.name": "API 密钥", "settings.apiKey.desc": "密钥保存在 Obsidian 安全存储中，不写入插件设置文件。", "settings.apiKey.local": "可留空（本地服务）", "settings.apiKey.placeholder": "请输入 API 密钥", "settings.retrieval.heading": "知识检索", "settings.retrieval.name": "检索模式", "settings.retrieval.desc": "精准扫描全部 Markdown；快速搜索已整理 Wiki。", "settings.retrieval.precise": "精准（推荐）", "settings.retrieval.fast": "快速",
  "command.rebuild": "重建知识索引", "command.profile": "显示识别到的知识库结构", "command.diagnostics": "显示知识索引诊断", "main.index.rebuilt": "Wiki Copilot 索引已重建。", "main.index.failed": "Wiki Copilot 索引失败：{{message}}", "main.progress.preparing": "正在准备本地知识索引…", "main.progress.planning": "正在生成检索关键词…", "main.progress.checking": "正在核对候选资料…", "main.progress.identifier": "正在校验本机精确标识符索引…", "main.progress.identifierRepaired": "已补齐 {{count}} 个标识符索引条目，正在重新检索…", "main.progress.files": "正在直接检查本机知识文件…", "main.progress.filesRepaired": "已补齐 {{count}} 个查询相关索引条目，正在重新检索…", "main.progress.missingIdentifier": "未找到精确标识符依据", "main.progress.hit": "已检索 {{count}} 个知识页面，{{service}}思考中…", "main.progress.miss": "未命中当前知识库，{{service}}思考中…", "main.progress.compatibility": "{{service}}思考中（兼容模式）…", "main.profile.pending": "知识库结构尚未识别完成。", "main.profile.schema": "Schema：{{value}}", "main.profile.index": "Index：{{value}}", "main.profile.wiki": "Wiki：{{value}}", "main.profile.sources": "来源：{{value}}", "main.unrecognized": "未识别", "main.diagnostics.device": "设备本地 IndexedDB", "main.diagnostics.vault": "Vault 插件目录", "main.diagnostics.disabled": "未启用", "main.diagnostics.active": "当前笔记：{{indexed}} · {{role}} · {{chunks}} 片段", "main.diagnostics.noActive": "当前笔记：未打开 Markdown", "main.diagnostics.cache": "缓存：{{value}}", "main.diagnostics.visible": "Obsidian 当前可见：{{count}} 个 Markdown", "main.diagnostics.tracked": "索引跟踪：{{count}} 个 Markdown", "main.diagnostics.wiki": "Wiki：{{files}} 页 / {{chunks}} 片段", "main.diagnostics.sources": "原文目录：{{count}} 页", "main.diagnostics.pending": "等待增量更新：{{count}} 项", "main.diagnostics.clear": "增量更新：无积压", "main.indexed": "已索引", "main.notIndexed": "未索引"
, "main.index.idle": "等待建立索引", "main.index.building": "正在建立知识索引…", "main.index.error": "索引失败", "main.progress.fast": "正在检索已整理的 Wiki 片段…", "main.progress.enumerating": "正在枚举全部 Markdown…", "main.progress.scanning": "正在扫描全部 Markdown…", "main.progress.extracting": "正在提取相关段落…", "main.answerTimeout.precise": "本地检索已完成，但 {{service}} 在 {{seconds}} 秒内未返回回答。请重试；若仍超时，可在设置中切换为“快速”检索。", "main.answerTimeout.fast": "本地检索已完成，但 {{service}} 在 {{seconds}} 秒内未返回回答。请稍后重试；若仍超时，可更换响应更快的模型。"
  , "view.history": "对话历史", "view.historySearch": "搜索对话历史", "view.historySearchPlaceholder": "搜索已保存的对话", "view.historySearchNoResults": "没有匹配的对话。", "view.historySearchExcerpt": "结果摘要：{{excerpt}}", "view.historyEmpty": "没有已保存的对话。", "view.openConversation": "打开对话：{{title}}", "view.deleteConversation": "删除对话：{{title}}", "view.deleteConversationConfirm": "要从 Vault 中删除\"{{title}}\"吗？", "view.delete": "删除", "view.cancel": "取消", "view.historyLoadFailed": "无法从 Vault 加载对话历史。", "view.historySaveFailed": "无法将此对话保存到 Vault。", "settings.conversation.heading": "对话历史", "settings.conversation.folder.name": "对话文件夹", "settings.conversation.folder.desc": "用于保存已完成对话的 Vault 文件夹。"
, "settings.model.includeRecentConversationContext.name": "包含最近对话上下文", "settings.model.includeRecentConversationContext.desc": "在普通模型请求中发送最近对话。即使关闭此项，紧邻的澄清回复仍会保持关联。", "settings.model.maximumInputTokens.name": "最大输入 Token", "settings.model.maximumInputTokens.desc": "自动、4000、6000、8000、12000、16000，或自定义整数。该限制为整个提示词预留安全余量。", "settings.model.maximumOutputTokens.name": "最大输出 Token", "settings.model.maximumOutputTokens.desc": "自动，或回答的整数上限，例如 512、1024 或 2048。", "settings.model.tokenLimit.placeholder": "自动或 Token 上限"
, "view.webSearch.compactAction": "搜索"
};
